// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dienzxkatkszkmbltuvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpZW56eGthdGtzemttYmx0dXZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MDc4OTQsImV4cCI6MjA2Mjk4Mzg5NH0.sNxpRLpBLlWH6fl3IptgRXPfmSh21tMr93kGJ3uZTSU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);